### ISSUE TITLE
Stake transfer

### ISSUE THREAD

**Issue by jjssoftware** [EOSIO/eosio.contracts#125]
Please implement the ability to immediately transfer stake between CPU <-> Network
Thanks!

**Comment by arhag** [comment]
I assume you mean without the 3 day delay? We intentionally do not allow immediate conversions between EOS staked for CPU bandwidth to/from EOS staked for network bandwidth, because otherwise it opens up an attack vector allowing multiple spends of bandwidth resources.

**Comment by jjssoftware** [comment]
Yes, when I said please implement the ability to immediately transfer stake between CPU <-> Network I had in mind the implementation of the ability to immediately transfer stake between CPU <-> Network with no 3 day delay / unstake wait period.

I'm disappointed that this has been closed with no explanation why there's no way to mitigate the double spend problem that you have described. The fact that it's not possible to transfer resources directly at this time is IMO a bug and the double spend problem that you have described sounds like a scenario that could be addressed as part of the fix.

**Comment by arhag** [comment]
@jjssoftware:

Okay. I will reopen this issue with the goal of facilitating discussion about potential solutions (or compromises) to workaround the double spend issue. I also I admit I may have been to quick to judge that the requested behavior would necessarily lead to the attack vector that we have already identified (and is the reason for the 3 day delays). It may be the case that the issue is not as severe for intra-account movements. I will have to spend more time thinking about the problem.

To be clear, reopening this issue is not a statement that we will definitely be implementing the requested behavior change (nor any of the other possibilities discussed below) in the reference system contract. But it is worth having a discussion about the possibilities and their various trade-offs, and brainstorm better solutions.

First, let me describe the well-identified problem in more detail. If a user can move staked tokens back and forth between accounts without restrictions, they would effectively be able to bypass any limits on their resources given how the resource limits code currently works. The user could consume all their resources quickly on one account; then after depleting those resources move the stake to another one of their accounts to deplete those resources again; and then repeat again and again. There would be no time delays on how quickly they could do this; if they had to wait one day between transition they would gain no advantage with this tactic compared to just keeping it all on one account since resources should fully replenish in one day anyway. 

I haven't yet thought through whether there even exists a better model for the resource limits algorithm that can avoids this issue. But even if there was, it would require a consensus protocol upgrade (commonly known as a hardfork) to change that algorithm.

There can be a variety of restrictions added at the system contract level on how staked tokens can be moved between accounts (or even between CPU and network within an account) that mitigates the resource abuse problem. We already have one restriction (the 3 day delay) that does a good job at preventing the attack vector, albeit it is probably more conservative than it needs to be. But it is possible to be more flexible with the restrictions in some scenarios without opening up a huge attack vector. 

We actually already have some flexibility already provided. For example, you are allowed to instantly move stake delegated to another account back to your account without a 3 day delay (simple `undelegatebw` to put the tokens in the unstaking queue, and then `delegatebw` to yourself and it will pull it from the unstaking queue first). However, instantly going the other way around is not allowed: `delegatebw` to another account will always pull from the liquid tokens and never the unstaking queue. Allowing instant movement of staked tokens in both direction would again open up the attack vector.

There may be potential for other flexibility in these restrictions as well. For example, perhaps the system contract could allow instant unstaking if the last time tokens were staked to the account were more than 2 days ago. I believe with this model, an attacker attempting to abuse the resource limits algorithm by taking advantage of this limited mechanism of instantaneous movement of staked tokens would be no better off then just keeping it all on one account. (Though I should spend more time analyzing that to be confident.)

In the case of moving staked tokens between CPU and network bandwidth, it may be the case that the abuse potential is very limited. Perhaps an attacker can use that mechanism to double their effective resources, but nor more than double. Again, I would need to spend more time analyzing these scenarios to be more confident in this assessment. But even if that is true, it is not clear if even that limited abuse is worth accepting to allow legitimate users more convenient movement of staked funds between CPU and network bandwidth.

**Comment by sanaraufx** [comment]
Introduction of the power up model has reduced the effectiveness of staking
