### ISSUE TITLE
Unable to compile using JSON parser

### ISSUE THREAD

**Issue by ekkis** [EOSIO/eosio.contracts#167]
I understand I should be able to use any library from the vast repertoire available in C++ within a smart contract.  at present I want to parse a JSON string so I've chosen lohmann's module, installed using Brew on OSX Mojave (v 10.14) with CDT v 1.4.1.  Here's what I did:

```
$ brew tap nlohmann/json
$ brew install nlohmann_json
$ brew test nlohmann_json
$ cat "#include <nlohmann/json.hpp>" > t.cpp
$ eosio-cpp -o t.wasm t.cpp --abigen
```

and what I get is:

> t.cpp:1:10: fatal error: 'nlohmann/json.hpp' file not found
> #include <nlohmann/json.hpp>
> ^~~~~~~~~~~~~~~~~~~
> 1 error generated.

I've posted an issue on lohmann's project though I think this is more an EOS problem: https://github.com/nlohmann/json/issues/1432

can anyone help?

**Comment by tbfleming** [comment]
This question doesn't involve any of the contracts in this repository; this type of question is better here: https://github.com/EOSIO/eosio.cdt

Many (probably most) libraries can't compile correctly into contracts since contracts don't run in a normal environment. e.g. standard I/O facilities are missing. In addition, libraries must be compiled to WASM. `brew` installs libraries compiled to native code. `eosio-cpp` can't pick up these libraries.

Use the CDT to compile libraries from source. Chances are high you'll have to write your own CMakeFile for any libraries you use, since those libraries won't have CMakeFiles tailored for the contract environment.

Contracts have an additional limitation: they can't use much memory and they can't use much CPU. JSON parsing tends to use a lot of both. We don't recommend parsing or producing JSON from within smart contracts.

**Comment by ekkis** [comment]
understood.  thank you
