### ISSUE TITLE
Name auction: auction doesn't close if previous winner hasn't registered account

### ISSUE THREAD

**Issue by moskvanaft** [EOSIO/eosio.contracts#21]

**Comment by andresberrios** [comment]
Hi! I just realized that we did duplicate work: https://github.com/EOSIO/eos/pull/4849
In the future, for pull requests on system contracts that should be deployed to the main net, should we use this repo or EOSIO/eos?
Thanks

**Comment by moskvanaft** [comment]
@andresberrios 
H! Now we use this repo for contracts.

**Comment by andresberrios** [comment]
@moskvanaft thanks! Any idea why this fix hasn't been deployed to the main net yet? What's the process for that?

**Comment by moskvanaft** [comment]
@andresberrios 
Version 1.1.1 of this repo was released yesterday - https://github.com/EOSIO/eosio.contracts/releases/tag/v1.1.1
Now it's up to block producers to upgrade the mainnet. I am not aware of their plans for now.

**Comment by blockminellc** [comment]
So how does this work. Per the actual rules of the bidding there should have been 20+ new names sold. 

1. It has been more than 24 hours since the last successful auction in the entire network
2. The price of the auction is the highest of the entire network
3. The price of the order lasts for more than 24 hours and no one bids again (every auction bid must be more than 10% of the current highest bid price)
4. The auction will start 2 weeks after the main network is activated

There is nothing that says a name must be registered to continue the auction???

 But since f2poolshenyu 2018-08-03 05:16:03 hasnt registered the name and at least one main block producer hasnt updated their code, those winners (via the convenants above) are being outbid - (re:.org). Does this mean once .app is registered and the subsequent that the new .org highest bidder will win, or chronologically the one that should have won it on the day  it should have won? I see lawsuits killing EOS and the BP's before this ever gets off the ground. We need a solution and ASAP.
