### ISSUE TITLE
Absence of a Doxyfile

### ISSUE THREAD

**Issue by ricktobacco** [EOSIO/eosio.contracts#351]
The contracts are annotated in a way that would be picked up by `doxygen`, but this is not sufficient to generate docs. 
A config file (Doxyfile) is necessary, and I am not sure how to go about coming up with that. I used the one from eosio.cdt, and the default on generated by `doxygen -g` to no avail. 
Can someone please help in coming up with a sufficient Doxyfile for this repo, so I can replicate the approach in my own repos?

**Comment by dskvr** [comment]
As the contract API has expanded, namely with the introduction of attributes and codegen, `eosio.contracts` compatibility has degraded. Doxygen has challenges parsing eosio.contracts due to these advanced implementations. We are exploring several alternatives:
1. [Standardese](https://github.com/standardese/standardese) - Requires some changes to build process, see [here](https://github.com/EOSIO/history-tools/blob/master/build-docs-base.dockerfile#L50-L62) for an example
2. Generic Javadoc Parsing - We're experimenting with this in the `docs/starter` branch. Since the execution of smart contract actions is primarily a matter of interface for the end user, any generic Javadoc parser provides good action reference documentation, without going into tree hierarchies and implementation. However, this has challenges due to attributes [[likethis]] confusing most parsers. For this reason, option 1 is the likely candidate long-term.

**Comment by ricktobacco** [comment]
Thank you for your reply,
So I implemented the modification to build process from the example, but still not sure how/where the standardese itself or the jsdoc-to-markdown, or gitbook client cli npm modules are being executed to pick up on the annotations in the files

**Comment by ricktobacco** [comment]
When I simply run standardese on the src directory, only the .abi files are getting picked up.

**Comment by ricktobacco** [comment]
@dskvr any suggestions, please?

**Comment by dskvr** [comment]
@ricktobacco Sorry for the late response 

- You would need to modify the annotations to work with Standardese. Standardese does not parse javadoc comments.
- We used javadoc, not jsdoc, and it requires some preprocessing to remove the "[[annotations]]" 

Again, we're moving towards standardese, if you would like to assist us with this transition, the first step is to change all the annotations to be standardese compatible.

**Comment by dskvr** [comment]
Please see https://github.com/EOSIO/eosio.contracts/issues/392

**Comment by iamveritas** [comment]
@ricktobacco is there anything else we can help with this issue? if not can we close it?
