### ISSUE TITLE
System contract upgrade -- EOS balance row should not be removed even it is zero

### ISSUE THREAD

**Issue by taokayan** [EOSIO/eosio.contracts#57]
replay from @eosbet-io 

When a new account is created, the system contract must be updated to create a zero balance entry for eosio.token. Currently, this zero entry is not in the table, so transactions through safetransfer contract are failing because the first EOS transfer into an account needs RAM.

The balance entry for any account in the eosio.token table should never be removed. All past removals need to be added back into the table as well, for the RAM fix to be successful.

**Comment by arhag** [comment]
There may be an argument for the system contract handler of new account to create a zero-balance table row in `eosio.token` for the core token symbol. To do this safely would require adding an `open` action to `eosio.token` to complement the existing `close` action, and have the system contract send an inline action to open that new table row.

The advantage of doing this is that it simplifies initialization of account to be a recipient of safetransfers of the core token, which I imagine nearly all accounts would want to receive since it is needed for staking and buying RAM. The disadvantage is that it increases the minimum amount of memory necessary to create an account, including accounts that may never need to receive any of the core tokens at all (for example RAM may be gifted to them, stake delegated to them, and they just have no need to deal with the core token at all for some reason).

Either way, initializing zero-balances on account creation is not a solution for any other token other than the core token, because there is an unbounded number of potential tokens a user might be interested in receiving via "safetransfer" / "proxy transfer" for example. 

Adding `eosio.token::open` (see #61) allows users to to pay for the RAM of the zero-balance table row for a particular token, so that future `eosio.token::transfer`s of that token do not incur any additional RAM costs.

Changing `eosio.token::transfer` behavior (see #62) to never create a table row if one does not already exist (which necessitates the `eosio.token::open` action being available so that there exists a way to actually transfer a new token to a user for the first time) would mean that `eosio.token::transfer` would by default become safe from the perspective of the sender not incurring unexpected RAM costs. With that change, there would be no need for the "safetransfer" and proxy contract workarounds.

So the path forward seems to be to implement `eosio.token::open` (#61) as soon as possible and then some time later change the behavior of `eosio.token::transfer` (#62). With `eosio.token::open` implemented, there is also the possibly of updating the system contract to automatically open a zero-balance table row for the core token symbol when a new account is created.
