### ISSUE TITLE
Contracts needs to self-identify version

### ISSUE THREAD

**Issue by jgiszczak** [EOSIO/eosio.contracts#70]
Now that the system contracts are no longer part of the base repository, and now that their release version number has diverged from the base software, the contract version in use on any particular chain needs to be identifiable in human-readable form remotely.

Contracts should respond to a `version` or `version_request` action.

**Comment by jjssoftware** [comment]
I was just discussing something similar in telegram but not related to system contracts, the discussion was more related to smart contracts in general. The question was around whether EOSIO smart contracts are verifiably safe given that all contracts are redeployable at any time.

I tabled the idea that it would be a nice security feature for smart contracts to publish an on-chain hash of themselves and then when once in-place security tested, the community could then have confidence that the code they're using is somewhat safe. If changed the hash changes and users know the code is then an unknown quantity. Going further we could couple this with a new property on a contract that points to an external 3rd party security audit report which contains the hash of the contract tested.

If this is where this issue is going then that's really great. If not, do you think this idea has any mileage?

**Comment by jgiszczak** [comment]
@jjssoftware Version 1.3.0 of the system contract includes a new table called `abihash`, which is precisely what you're looking for.  See the [release notes](https://github.com/EOSIO/eosio.contracts/releases) for details.

**Comment by jjssoftware** [comment]
That's phenomenal @jgiszczak, block one has reached new levels of psychic ability (or maybe I have) :)
