### ISSUE TITLE
EOSIO 1.3 not supported

### ISSUE THREAD

**Issue by zxcat** [EOSIO/eosio.contracts#81]
Fails with `Incorrect EOSIO version, please use version 1.2.x`.
Is it bug or feature?

**Comment by zxcat** [comment]
BTW, builds fine with EOSIO 1.3 and all tests passed
```
Running 78 test cases...

*** No errors detected
```

**Comment by warrick-eosny** [comment]
This is breaking some of my automated builds ... can someone please fix this ASAP

**Comment by arhag** [comment]
It is a feature, but one that is perhaps too conservative to be useful, especially given our staggered minor release schedule of eosio and eosio.contracts. We only bump the version dependencies on minor releases (i.e. 1.X.0) rather than on patch releases. So this should be resolved with the v1.4.0 release of contracts. Until then you can bypass the safety check as described by @zxcat.

In a future release we will relax the version checks to support a hard minimum version, a soft maximum version, and an optional hard maximum version. Assuming the found version does not exceed the hard maximum (if present), then the build will continue even if the found version is greater than the soft maximum (although in that case it will print a warning to the console).

**Comment by arhag** [comment]
Resolved by #89.
